// src/lib/pricing.ts

export const PLANS = [
  {
    id: "plan-bronze",
    name: "برنز",
    cpu: "0.5 هسته",
    ram: "0.5 گیگابایت",
    disk: "5 گیگابایت",
    bandwidth_gb: 50,
    price: 40000,
    is_active: true,
    is_locked: false,
    sort: 1,
  },
  {
    id: "plan-silver",
    name: "نقره",
    cpu: "0.75 هسته",
    ram: "1 گیگابایت",
    disk: "10 گیگابایت",
    bandwidth_gb: 100,
    price: 60000,
    is_active: true,
    is_locked: false,
    sort: 2,
  },
  {
    id: "plan-gold",
    name: "طلا",
    cpu: "1 هسته",
    ram: "2 گیگابایت",
    disk: "20 گیگابایت",
    bandwidth_gb: 200,
    price: 80000,
    is_active: true,
    is_locked: false,
    sort: 3,
  },
  {
    id: "plan-diamond",
    name: "الماس",
    cpu: "1.5 هسته",
    ram: "4 گیگابایت",
    disk: "30 گیگابایت",
    bandwidth_gb: 300,
    price: 100000,
    is_active: true,
    is_locked: false,
    sort: 4,
  },
  {
    id: "plan-ruby",
    name: "یاقوت",
    cpu: "2 هسته",
    ram: "6 گیگابایت",
    disk: "40 گیگابایت",
    bandwidth_gb: 400,
    price: 140000,
    is_active: true,
    is_locked: false,
    sort: 5,
  },
  {
    id: "plan-galaxy",
    name: "کهکشان",
    cpu: "2.5 هسته",
    ram: "8 گیگابایت",
    disk: "50 گیگابایت",
    bandwidth_gb: 500,
    price: 180000,
    is_active: true,
    is_locked: false,
    sort: 6,
  },
];

export const ADDONS = [
  { id: "addon-ram", name: "+۱GB رم", price: 30000, is_active: true, is_locked: false },
  { id: "addon-disk", name: "+۱۰GB دیسک", price: 20000, is_active: true, is_locked: false },
];
